name: Build and Publish Docker image
on:
  workflow_dispatch:
  push:
    branches: [main, stage, '*/*']

env:
  REPOSITORY_NAME: hdce/nginx-ssl-proxy

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Push to ECR
        uses: harvard-edtech/dce-ecr-action@v1.3
        id: build_and_push
        with:
          access_key_id: ${{ secrets.PUSH_TO_ECR_AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.PUSH_TO_ECR_AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: ${{ env.REPOSITORY_NAME }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          tags: sha-${{ github.sha }}
          add_branch_tag: true
          add_package_version_tag_for_branch: main
          slack_webhook_url: ${{ secrets.PUSH_TO_ECR_SLACK_NOTIFY_WEBHOOK_URL }}
