# this will build and push an image to an ECR repo identified by
# the REPOSITORY_NAME env setting. Any branch matching the pattern
# */*, e.g., bugfix/some-bug, will be built and the resulting image
# tagged, e.g., bugfix-some-bug

name: Build and Push Image to ECR

on:
  workflow_dispatch:
  push:
    branches: [main, stage, "*/*"]

permissions:
  contents: read
  actions: read

jobs:
  build_and_push:
    name: "Build and push image to ECR"
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: harvard-dce/dce-build-and-push/.github/workflows/reusable-build-and-push.yml@main
    with:
      repository_name: hdce/nginx-ssl-proxy
      version_tag_this_branch: main
      base_image_name: nginx:1.30.2-alpine
      version_command: "tr -d '[:space:]' < ./version.txt"
    secrets:
      AWS_PUSH_TO_ECR_OIDC_ROLE: ${{ secrets.AWS_PUSH_TO_ECR_OIDC_ROLE }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
